name: Build CatCore.Emoji

on:
    workflow_dispatch:
    push:
        branches: [ main ]
        paths:
            - 'CatCore.Emoji/**'
            - '.github/workflows/main.yml'
    pull_request:
        branches: [ main ]
        paths:
            - 'CatCore.Emoji/**'
            - '.github/workflows/main.yml'

jobs:
    catcore-emoji-models:
        name: Handle CatCore.Emoji.Models
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup dotnet
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 6.0.100
            - name: Build CatCore.Emoji.Models
              id: Build
              run: dotnet build CatCore.Emoji.Models --configuration Release
            - name: Pack CatCore.Emoji.Models
              id: Pack
              run: dotnet pack CatCore.Emoji.Models --configuration Release --output Publish
            - name: Authenticate to GitHub Package Registry
              id: Authenticate
              run: dotnet nuget add source --username ${ REPOSITORY_OWNER } --password ${ GITHUB_TOKEN } --store-password-in-clear-text --name github ${ REPOSITORY_URL }
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  REPOSITORY_OWNER: ${{ github.repository_owner }}
                  REPOSITORY_URL: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
            - name: Publish CatCore.Emoji.Models Nuget to GitHub Package Registry
              id: Publish
              run: dotnet nuget push ./Publish/*.nupkg -k $GITHUB_TOKEN -s --source "github" --skip-duplicate
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    catcore-emoji-sourcegeneration-gnoto:
        name: Handle CatCore.Emoji.SourceGeneration.GNoto
        runs-on: ubuntu-latest
        needs: catcore-emoji-models
        steps:
            - uses: actions/checkout@v2
            - name: Setup dotnet
              uses: actions/setup-dotnet@v1
              with:
                    dotnet-version: 6.0.100
            - name: Build
              id: Build
              run: dotnet build CatCore.Emoji.SourceGeneration.GNoto --configuration Release
            - name: Run CatCore.Emoji.SourceGeneration.GNoto Unit Tests
              id: Test
              run: dotnet test CatCore.Emoji.SourceGeneration.GNoto.UnitTests --configuration Release
            - name: Pack CatCore.Emoji.SourceGeneration.GNoto
              id: Pack
              run: dotnet pack CatCore.Emoji.SourceGeneration.GNoto --configuration Release --output Publish
            - name: Authenticate to GitHub Package Registry
              id: Authenticate
              run: dotnet nuget add source --username ${ REPOSITORY_OWNER } --password ${ GITHUB_TOKEN } --store-password-in-clear-text --name github ${ REPOSITORY_URL }
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  REPOSITORY_OWNER: ${{ github.repository_owner }}
                  REPOSITORY_URL: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
            - name: Publish CatCore.Emoji.SourceGeneration.GNoto Nuget to GitHub Package Registry
              id: Publish
              run: dotnet nuget push ./Publish/*.nupkg -k ${GITHUB_TOKEN} -s --source "github" --skip-duplicate
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}